### ISSUE TITLE
Test output for ray tracing gives erroneous turning height, range, travel time values

### ISSUE THREAD

**Issue by liamtoney** [chetzer-ncpa/ncpaprop#17]
I've installed **ncpaprop** on a Linux machine running CentOS 7.6.1810. The install was successful but `make test` fails with the following output:
```console
*** Checking 2D Ray Theory Calculation Results ***
/opt/antelope/5.4/bin/perl compare_raytrace.2d_test
Test failed for Elevation: 1 in raytrace.2d test!
make: *** [compare.raytrace.2d] Error 1
```

Upon inspection of the top of my `testlog.txt`, I find the following erroneous values:
```
<<raytrace.2d>>
Ray Trace Parameters:
Atmospheric File Name: NCPA_canonical_profile_zuvwtdp.dat
Maximum Height: 140 km
Launch Azimuth: 90
Launch Elevation: [1,1,45]

Starting calculation...


Calculating theta = 1 degrees...
Maximum number of skips reached.
Ray trace for angle theta = 1 completed.
Max Turning Height: 53.1521 km
Skips: 1
Range: 343.486 km
Travel Time: 361.188 seconds (6.0198 minutes)
Celerity: 0.95099 km/s
Transmission Loss re ~1km: -29.2661 dB


Calculating theta = 2 degrees...
Maximum number of skips reached.
Ray trace for angle theta = 2 completed.
Max Turning Height: 53.2718 km
Skips: 1
Range: 341.619 km
Travel Time: 359.46 seconds (5.991 minutes)
Celerity: 0.950368 km/s
Transmission Loss re ~1km: -29.6248 dB
```
Clearly, the celerities are nonsensical. The range, travel time, and turning height values do not agree with the [`testlog.txt`](https://github.com/chetzer-ncpa/ncpaprop/blob/master/test/testlog.txt) provided here on GitHub, either. I will modify the testing script to see if the issue is confined only to the ray tracing codes.

**Comment by liamtoney** [comment]
Commenting out the two lines in [`test/Makefile`](https://github.com/chetzer-ncpa/ncpaprop/blob/master/test/Makefile) which do the ray tracing comparisons allows the test process to fully run. Other comparisons are OK.

**Comment by dtailpied** [comment]
Hello, 
I got exactly the same issue. It is running but when we take a look at the results it gives erroneous values and does not match with what we should get. 
Did you find where the problem was coming from at the end? 
Same things are observed for both ray_tracing (2d and 3d), and the comparisons work for the other (even though the files that we are not comparing do not have the same values, celerity issue..).

**Comment by chetzer-ncpa** [comment]
After a period of no funding, I am preparing to do a deep dive and major revision of this package.  I will attempt to nail this error down early in the process.  I have heard this issue several times recently and I believe it to be an issue related to some code incompatibility with the latest compiler versions; other users have reported error messages that appear to be related to the declaration of const floating-point variables due to the updated code standards in gcc 7.  I will update when I know more.  Thank you for bringing it back to my attention.
________________________________

**Comment by chetzer-ncpa** [comment]
Please pull the latest version and try again.  I believe this was a units issue in the sample atmosphere file.

**Comment by liamtoney** [comment]
After pulling the most recent version, `make test` fails on:
```
*** Running One-Way Coupled Modal Routines ***
/bin/bash run_ModessRD1WCM_test.bash >> ./testlog.txt
mv: tloss_rd_1d.lossless.nm: No such file or directory
mv: tloss_rd_1d.nm: No such file or directory
make[1]: *** [calculate.modessrd1wcm] Error 1
make: *** [test] Error 2
```
Within `test/testlog.txt` the error seems to be related to units.
```
 --------------------------------------------------------------
 ERROR!
 It appears that ducting conditions are not formed and
 modes will not exist because the effective sound speed
 at the top is smaller than the sound speed at the ground.
  cefftop   = -32582.3 m/s
  ceff_grnd = 1496.06 m/s
  ceffmin   = -32944.8 m/s
 Suggest increasing maxheight and checking your profile file.
 --------------------------------------------------------------
```
I tried skipping this test, but I ran into issues with the ray-tracing tests as well.

**Comment by chetzer-ncpa** [comment]
Ray tracing tests are showing errors that I think are related to floating-point rounding, tests need to be rewritten.  I concur that errors in ModessRD1WCM is likely wind speed units, probably a flag that is improperly set in the test command.  Will be investigating in the next few days.

**Comment by chetzer-ncpa** [comment]
ModessRD1WCM bug should be fixed.  I had found some spots where the wind units were being improperly determined in the recent overhaul, but there were some other spots where I had missed it.  I have not gotten the ray tracing test fixed yet (it wants to look at the result at 6km but ends up with one at 6.00001 km, obviously a rounding issue) so I have temporarily disabled those so that the rest of the tests can run to completion.  I get successful tests on my development machine.
